[build]
command = "npm run build" # Perintah build untuk aplikasi client
functions = "client" # Folder untuk serverless functions
publish = "/" # Folder output dari build aplikasi client

[[redirects]]
from = "/*"
to = "client/index.html"
status = 200